name: CI Angular - Alisson

on:
  push:
    branches:
      - 'branch_Alisson'
  pull_request:
  workflow_call:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        
    - name: Install dependencies
      run: npm install
  
    - name: Run tests
      run: npm run test --no-watch --no-progress --browsers=ChromeHeadless
      
    - name: Build
      run: npm run build
